In [47]:
import pandas as pd
import random

In [49]:
sessions = pd.read_csv("airbnb/sessions.csv")
print (sessions.shape)
sessions.head()

(10567737, 6)

,user_id,action,action_type,action_detail,device_type,secs_elapsed
0,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,319.0
1,d1mm9tcy42,search_results,click,view_search_results,Windows Desktop,67753.0
2,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,301.0
3,d1mm9tcy42,search_results,click,view_search_results,Windows Desktop,22141.0
4,d1mm9tcy42,lookup,NaN,NaN,Windows Desktop,435.0

In [50]:
train = pd.read_csv("airbnb/train_users_2.csv")
print (train.shape)
train.head()

(213451, 16)

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,2010-06-28,20090319043255,NaN,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF
1,820tgsjxq7,2011-05-25,20090523174809,NaN,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,NDF
2,4ft3gnwmtx,2010-09-28,20090609231247,2010-08-02,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,US
3,bjjt8pjhuk,2011-12-05,20091031060129,2012-09-08,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,other
4,87mebub9p4,2010-09-14,20091208061105,2010-02-18,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,US

In [40]:
user_idx = random.randrange(0, train.shape[0])
user_id = train.loc[user_idx]["id"]
print (user_id)
user_sessions = sessions[sessions["user_id"] == user_id]
user_sessions.head()

tbchxrlbky

,user_id,action,action_type,action_detail,device_type,secs_elapsed
3169522,tbchxrlbky,similar_listings,data,similar_listings,Mac Desktop,0.0
3169523,tbchxrlbky,show,view,p3,Mac Desktop,358.0
3169524,tbchxrlbky,ajax_lwlb_contact,click,contact_host,Mac Desktop,36771.0
3169525,tbchxrlbky,similar_listings,data,similar_listings,Mac Desktop,1155.0
3169526,tbchxrlbky,ajax_check_dates,click,change_contact_host_dates,Mac Desktop,31.0

In [51]:
actions = sessions["action"].values

actions = list(set(actions))
len(actions)

360

In [ ]:
for user_idx in range(0, train.shape[0]):
    user_info = train.loc[user_idx][["id", "country_destination"]]
    if user_info["country_destination"] == "NDF":
        continue
        
    user_id = user_info["id"]
    print ("user id : " + user_id)
    user_sessions = sessions[sessions["user_id"] == user_id]
                                    
    for action in actions:
        count = user_sessions[user_sessions["action"] == action].shape[0]
        if count:
            print ("action ({}) - count({})".format(action, count))
  
    print ("-----------" * 8)

user id : 4ft3gnwmtx
----------------------------------------------------------------------------------------
user id : bjjt8pjhuk
----------------------------------------------------------------------------------------
user id : 87mebub9p4
----------------------------------------------------------------------------------------
user id : osr2jwljor
----------------------------------------------------------------------------------------
user id : lsw9q7uk0j
----------------------------------------------------------------------------------------
user id : 0d01nltbrs
----------------------------------------------------------------------------------------
user id : a1vcnhxeij
----------------------------------------------------------------------------------------
user id : 6uh8zyj2gn
----------------------------------------------------------------------------------------
user id : yuuqmid2rp
----------------------------------------------------------------------------------------
user id : k6np330cm1
----------------------------------------------------------------------------------------
user id : v4d5rl22px
----------------------------------------------------------------------------------------
user id : frhre329au
----------------------------------------------------------------------------------------
user id : gdka1q5ktd
----------------------------------------------------------------------------------------
user id : qdubonn3uk
----------------------------------------------------------------------------------------
user id : qsibmuz9sx
----------------------------------------------------------------------------------------
user id : 80f7dwscrn
----------------------------------------------------------------------------------------
user id : al8bcetz0g
----------------------------------------------------------------------------------------
user id : hfrl5gle36
----------------------------------------------------------------------------------------
user id : tp6x3md0n4
----------------------------------------------------------------------------------------
user id : hql77nu2lk
----------------------------------------------------------------------------------------
user id : cheova4spt
----------------------------------------------------------------------------------------
user id : 7my0vrljxc
----------------------------------------------------------------------------------------
user id : k15j7mbny0
----------------------------------------------------------------------------------------
user id : g3z67e37mb
----------------------------------------------------------------------------------------
user id : g1q6caq452
----------------------------------------------------------------------------------------
user id : f6mzhb4wbc
----------------------------------------------------------------------------------------
user id : ngai8kt2yi
----------------------------------------------------------------------------------------
user id : byozd991xf
----------------------------------------------------------------------------------------
user id : rcx09dn2je
----------------------------------------------------------------------------------------
user id : ae59m0iqsx
----------------------------------------------------------------------------------------
user id : efabqzuxmf
----------------------------------------------------------------------------------------
user id : emg8edpcpm
----------------------------------------------------------------------------------------
user id : ehcdcpkn8y
----------------------------------------------------------------------------------------
user id : fp6ndcm5ak
----------------------------------------------------------------------------------------
user id : ranh94tmin
----------------------------------------------------------------------------------------
user id : 0xvbruzuzz
----------------------------------------------------------------------------------------
user id : mz47bohqc8
----------------------------------------------------------------------------------------
user id : b9gu8uoxxw
----------------------------------------------------------------------------------------
user id : h53mz152m4
----------------------------------------------------------------------------------------
user id : b9pzliufcj
----------------------------------------------------------------------------------------
user id : h2gn4f9oqa
----------------------------------------------------------------------------------------
user id : jf5oxeb233
----------------------------------------------------------------------------------------
user id : jzw5p68a5u
----------------------------------------------------------------------------------------
user id : rxdkzkowt2
----------------------------------------------------------------------------------------
user id : prqnudhgdx